import Head from 'next/head';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Check, MapPin, PiggyBank } from 'lucide-react';
import { partners, type ActivePartner } from '../../lib/partners';
import DecisionGateway from '../../components/DecisionGateway';

export default function BredbandAdress() {
  const active=(name:string)=>partners.find((p):p is ActivePartner=>p.name===name&&p.status==='active'&&typeof p.trackingUrl==='string'&&p.trackingUrl.length>0);
  const broadbandval=active('Bredbandsval.se');
  const internetport=active('Internetport');
  return <><Head><title>Bredband på min adress 2026 – jämför alternativ | Sänk Kostnaden</title><meta name='description' content='Så kontrollerar du vilket bredband som finns på din adress och jämför fiber, kabel och mobilt bredband på pris, hastighet och villkor.'/><link rel='canonical' href='https://sankkostnaden.se/bredband/bredband-pa-min-adress/'/><script type='application/ld+json' dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:"Bredband på min adress 2026 – jämför alternativ",description:"Så kontrollerar du vilket bredband som finns på din adress och jämför fiber, kabel och mobilt bredband på pris, hastighet och villkor.",url:"https://sankkostnaden.se/bredband/bredband-pa-min-adress/",isPartOf:{'@type':'WebSite',name:'Sänk Kostnaden',url:'https://sankkostnaden.se/'}})}} /></Head><header className='topbar'><Link className='brand' href='/'><span className='brandMark'><PiggyBank size={22}/></span><span>Sänk Kostnaden</span></Link><nav><Link href='/bredband/'>Bredband</Link><Link href='/elavtal/'>El</Link><Link href='/mobil/'>Mobil</Link><Link href='/forsakring/'>Försäkring</Link><Link href='/ekonomi/'>Ekonomi</Link></nav><Link className='topbarCta' href='/#jamfor'>Jämför priser →</Link></header><main><section className='guideHero guideHero-bredband'><div className='guideWrap'><Link className='back' href='/bredband/'><ArrowLeft size={16}/> Bredband</Link><div className='guideIcon'><MapPin size={25}/></div><p className='kicker'>BREDBAND</p><h1>Bredband på min adress – se vad som finns</h1><p className='lead'>Bredband är lokalt. Börja därför med adressens nät och jämför därefter pris och hastighet mellan de operatörer som faktiskt kan leverera.</p>{(broadbandval||internetport) && <><div className='heroPartnerActions'>
  {broadbandval&&<a className='primary' href={broadbandval.trackingUrl} data-partner={broadbandval.name} data-category='bredband' data-intent='compare' data-placement='hero' target='_blank' rel='sponsored nofollow noopener'>Jämför utbud på adressen hos Bredbandsval.se <ArrowUpRight size={17}/></a>}
  {internetport&&<a className='secondaryLight' href={internetport.trackingUrl} data-partner={internetport.name} data-category='bredband' data-intent='compare' data-placement='hero_secondary' target='_blank' rel='sponsored nofollow noopener'>Se bredband hos Internetport <ArrowUpRight size={17}/></a>}
</div><p className='fine'>Annonslänkar · tillgänglighet och aktuella priser kontrolleras hos respektive tjänst</p></>}</div></section><article className='article guideWrap'><DecisionGateway category='bredband' intent='compare' /><h2>Gör adresskontrollen i rätt ordning</h2><div className='checkList'>{['Kontrollera om bostaden har fiber eller kabelnät','Se vilka operatörer som är valbara i nätet','Jämför samma hastighetsnivå','Räkna ordinarie pris efter kampanj','Kontrollera bindningstid och routerkostnad'].map(x=><p key={x}><Check size={18}/>{x}</p>)}</div><div className='partnerBox'><p className='partnerEyebrow'>BREDBANDSKOLL</p><h3>Kontrollera bredband och erbjudanden</h3><p>Börja med adressen eftersom utbud och pris varierar mellan nät. Jämför därefter samma hastighet, ordinarie pris, kampanjperiod, router och bindningstid.</p><Link className='primary' href='/bredband/billigaste-bredbandet/'>Jämför bredband steg för steg</Link></div><h2>Fiber är inte automatiskt billigast</h2><p>Fiber ger ofta hög kapacitet och flera leverantörsval, men priset beror på nät och operatör. För vissa hushåll kan kabel eller mobilt bredband vara ekonomiskt rimligt. Jämför alltid total månadskostnad för en tillräcklig hastighet.</p><h2>Hur hög hastighet ska du välja?</h2><p>Betala inte för mer än hushållet behöver. Läs <Link href='/bredband/vilken-hastighet-behover-jag/'>hur snabbt bredband du behöver</Link> och gå sedan vidare till vår guide om <Link href='/bredband/billigaste-bredbandet/'>billigaste bredbandet</Link>.</p><p className='disclosure'>Kommersiell information: operatörslänkar markeras som reklam/annonslänkar. Tillgänglighet måste alltid kontrolleras för den aktuella adressen.</p></article></main></>;
}
